# Generated by Django 4.0.5 on 2022-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_from_user_alter_message_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by',
            field=models.TextField(default=''),
        ),
    ]
